### PR TITLE
Expand metadata and depend on mildly modern apt/yum/windows

### PR DESCRIPTION
**Pull request by tas50**
## Description

A few minor cleanup commits, expansion of the metadata with chef_version, and the requirement that the user have apt 2.0 and yum 3.0, which ensures they have apt/yum that will work with this cookbook. Also require a windows cookbook that is compatible with Chef 12.

## Motivation and Context
Just some general cleanup

## How Has This Been Tested?
Test Kitchen can't resolve deps without Berks or Policyfiles so I'm unable to run a Test Kitchen run on this, but it's all pretty straight forward

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.

### CODE REVIEW

**Comment by tas50** [comment]
Technically this is a breaking change for people on ANCIENT apt/yum cookbooks, but I'm not sure I'd call that a breaking change in Semver standards.

**Comment by cwjohnston** [comment]
@tas50 thanks for the PR. I'm pretty sure that the added platforms won't converge atm but I will take a look. 

When you say 
> Test Kitchen can't resolve deps without Berks or Policyfiles

am I correct in inferring that this because you're using ChefDK and librarian-chef isn't available to you? Just trying to understand scope of the problem here.

**Comment by tas50** [comment]
Even with librarian-chef installed into chef-dk it never resolves the ms_dotnet cookbook when running kitchen.

**Comment by cwjohnston** [comment]
@tas50 I have also had difficulty with librarian-chef recently. I've found that excluding ms_dotnet doesn't solve it for me but [locking yum < 4.0 does](https://github.com/sensu/sensu-chef/pull/497/files#diff-ef0ab806c03b09ac321d65dd0a9449f2R5). Any ideas why this might be? I couldn't see an obvious reason.

**Comment by cwjohnston** [comment]
Update: if i pin yum = 4.0, librarian-chef is fine

**Comment by portertech** [comment]
Now that Librarian has been replaced, the yum lock can be tossed \o/

**Comment by tas50** [comment]
Can we merge this at this point then? I'd like to work on another PR for some integration testing now that we have Berkshelf in place.

**Comment by cwjohnston** [comment]
@tas50 test-kitchen suites sysv-ubuntu-1604 and sysv-centos-72 are failing for me locally.
I think the failures are due to systemd weirdness where the service is allegedly "dead" on first start (but actually running) so serverspec assertions that services should be running fail. I'm not completely sure, but this may not be fixed until we ship changes slated for Sensu 0.27.

Should we remove those two platforms until we can reasonably assert they will work?

**Comment by tas50** [comment]
I wouldn't take inclusion in test kitchen as supported. It just means we have the means to test. They'll be there to further debug and improve things as time goes on.

**Comment by cwjohnston** [comment]
Lets do it.

**Pull request merged**
