### PR TITLE
Fix chef-vault integration in Sensu::Helpers

### PR DESCRIPTION
**Pull request by martinisoft**
I hit this bug in production and it's a sneaky one. This test case forces the [encrypted guard](https://github.com/sensu/sensu-chef/blob/81e88fdaedc3926fb9eb0416fc40992464021cdd/libraries/sensu_helpers.rb#L40-L45) to actually call the chef_vault_item method as it was being bypassed before. So now the new issue I cannot resolve is, how to include the other chef-vault module and get this passing.

Here is the backtrace you get:

```
================================================================================
Recipe Compile Error in /tmp/kitchen/cache/cookbooks/sensu-test/recipes/default.rb
================================================================================

       NoMethodError
       -------------
       undefined method `chef_vault_item' for Sensu::Helpers:Class

       Cookbook Trace:
       ---------------
         /tmp/kitchen/cache/cookbooks/sensu/libraries/sensu_helpers.rb:47:in `data_bag_item'
         /tmp/kitchen/cache/cookbooks/sensu/recipes/rabbitmq.rb:82:in `from_file'
         /tmp/kitchen/cache/cookbooks/sensu-test/recipes/default.rb:35:in `from_file'

       Relevant File Content:
       ----------------------
       /tmp/kitchen/cache/cookbooks/sensu/libraries/sensu_helpers.rb:

        40:          encrypted = raw_hash.detect do |key, value|
        41:            if value.is_a?(Hash)
        42:              value.has_key?("encrypted_data")
        43:            end
        44:          end
        45:          if encrypted
        46:            if Chef::DataBag.load("sensu").key? "#{item}_keys"
        47>>             chef_vault_item("sensu", item)
        48:            else
        49:              secret = Chef::EncryptedDataBagItem.load_secret
        50:              Chef::EncryptedDataBagItem.new(raw_hash, secret)
        51:            end

        53:            raw_hash
        54:          end
        55:        rescue Chef::Exceptions::ValidationFailed,
        56:          Chef::Exceptions::InvalidDataBagPath,


       Running handlers:

       Running handlers complete
       [2015-02-03T23:14:00+00:00] ERROR: Exception handlers complete

       Chef Client failed. 0 resources updated in 7.727011328 seconds
       [2015-02-03T23:14:00+00:00] ERROR: undefined method `chef_vault_item' for Sensu::Helpers:Class
       [2015-02-03T23:14:02+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

### CODE REVIEW

**Comment by martinisoft** [comment]
@jtimberman just [commited this change](https://github.com/opscode-cookbooks/chef-vault/blob/13e02491695025cca20920fdb3acf8a01d9aa1bf/libraries/chef_vault_item.rb#L23-L45) to make it a module, which should make things easier for accessing the Chef Vault helper.

**Comment by martinisoft** [comment]
I have updated this pull request with what is now a passing test based upon the current master version of chef-vault. We can wait on @jtimberman to officially cut a release (I think he's waiting on another PR merge) before updating this and merging. 

/cc @portertech

**Comment by martinisoft** [comment]
Got this ready to be reviewed for merge as chef-vault 1.2.0 just released with this change.

**Comment by portertech** [comment]
@martinisoft Can we get this working w/o the chef-vault dependency?

**Comment by martinisoft** [comment]
@portertech Turns out you don't need to list it in the main cookbook (just the wrapper) to get it to load. Just resolved this with the latest commit.

**Comment by martinisoft** [comment]
@portertech I've added in the const_defined? check and it's good to go. So now if chef-vault is unavailable it will still throw a NoMethodError as before. We can rescue it separately in that helper method and provide a friendlier error message to remind someone to include chef-vault in their metadata.

**Comment by portertech** [comment]
:+1:

**Pull request merged**
